// <auto-generated />
using System;
using GithubCommitsToMusic.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GithubCommitsToMusic.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250823164823_pendingchanges")]
    partial class pendingchanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GithubCommitsToMusic.Models.Commit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Commits", (string)null);
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.Music", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Musics", (string)null);
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.Query", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Queries", (string)null);
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.Sheet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Note")
                        .HasColumnType("int");

                    b.Property<string>("VirtualPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sheets", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Do.wav",
                            Note = 0,
                            VirtualPath = "/Sheets/Do.wav"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Re.wav",
                            Note = 1,
                            VirtualPath = "/Sheets/Re.wav"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Mi.wav",
                            Note = 2,
                            VirtualPath = "/Sheets/Mi.wav"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Fa.wav",
                            Note = 3,
                            VirtualPath = "/Sheets/Fa.wav"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Sol.wav",
                            Note = 4,
                            VirtualPath = "/Sheets/Sol.wav"
                        },
                        new
                        {
                            Id = 6,
                            Name = "La.wav",
                            Note = 5,
                            VirtualPath = "/Sheets/La.wav"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Si.wav",
                            Note = 6,
                            VirtualPath = "/Sheets/Si.wav"
                        });
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.Commit", b =>
                {
                    b.HasOne("GithubCommitsToMusic.Models.User", "User")
                        .WithMany("Commits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.Music", b =>
                {
                    b.HasOne("GithubCommitsToMusic.Models.User", "User")
                        .WithMany("Musics")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("GithubCommitsToMusic.Models.User", b =>
                {
                    b.Navigation("Commits");

                    b.Navigation("Musics");
                });
#pragma warning restore 612, 618
        }
    }
}
