services:
  mssql-1:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: Y
    ports:
      - 1433:1433 # Corrected default MSSQL port
    networks:
      - web-api
    volumes:
      - mssql-data:/var/opt/mssql

  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - "5511:8080" # Match the ASPNETCORE_URLS port
    depends_on:
      - mssql-1
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - generated-music-data:/app/wwwroot/Sheets/GeneratedMusics:drwxr-xr-x+
    command: sh -c "chmod 777 /app/wwwroot/Sheets/GeneratedMusics/ && dotnet GithubCommitsToMusic.dll --environment=Release" # Changed to chmod 777
    networks:
      - web-api

  frontend:
    container_name: frontend
    build:
      context: ../Frontend # Build from the Frontend directory
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.commitstomusic.yunusozdemirr.com
    depends_on:
      - web-api
    networks:
      - web-api
networks:
  web-api:
    name: web-api

volumes:
  mssql-data:
  generated-music-data: