services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "yourStrong(!)Password"
      ACCEPT_EULA: Y
    ports:
      - 1434:1434
    networks:
      - web-api
    volumes:
      - mssql-data:/var/opt/mssql

  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: Web.Api/Dockerfile
    ports:
      - "5511:8080" # Match the ASPNETCORE_URLS port
    depends_on:
      - mssql
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - /home/admin/Sheets:/wwwroot/Sheets
    networks:
      - web-api

  frontend:
    container_name: frontend
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=https://api.commitstomusic.yunusozdemirr.com
    depends_on:
      - web-api
    networks:
      - web-api

networks:
  web-api:
    name: web-api

volumes:
  mssql-data: